apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: assignment02
  name: pvc-mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: linode-block-storage